name: blog
title: Blog
description: A standard blog manager with additional categories and authors datatable.
version: 1.0
category: Marketing
author: Solodev
authorWebsite: https://www.solodev.com/
projectURL: https://github.com/solodev/marketplace/managers/blog/
featuredImage: featured-image.jpg
entryPoint:
    path: /Blog
    type: Calendar